on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: ci

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./.docker/Dockerfile
          tags: mdshack/shotshare:ci
          outputs: type=docker,dest=${{ runner.temp }}/image.tar

      - name: Upload docker image
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: ${{ runner.temp }}/image.tar

  unit-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download docker image
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: ${{ runner.temp }}/image.tar

      - name: Load docker image
        run: docker load --input ${{ runner.temp }}/image.tar

      - uses: addnab/docker-run-action@v3
        with:
          image: mdshack/shotshare:ci
          run: /app/vendor/bin/pest

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download docker image
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: ${{ runner.temp }}/image.tar

      - name: Load docker image
        run: docker load --input ${{ runner.temp }}/image.tar

      - uses: addnab/docker-run-action@v3
        with:
          image: mdshack/shotshare:ci
          run: /app/vendor/bin/pint --test

  # static-analysis:
  #   runs-on: ubuntu-latest
  #   steps:
