on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: ci

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP with fail-fast
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - run: composer install --no-interaction

      - run: |
          npm ci
          npm run build

      - run: chmod +x ${{ github.workspace }}/vendor/bin/pest ${{ github.workspace }}/vendor/bin/pint

      - name: Upload workspace
        uses: actions/upload-artifact@v4
        with:
          name: workspace
          path: ${{ github.workspace }}

  unit-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace
          path: ${{ github.workspace }}

      - name: Run unit tests
        run: |
          chmod +x ${{ github.workspace }}/vendor/bin/pest
          ${{ github.workspace }}/vendor/bin/pest

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace
          path: ${{ github.workspace }}

      - name: Run unit tests
        run: |
          chmod +x ${{ github.workspace }}/vendor/bin/pint
          ${{ github.workspace }}/vendor/bin/pint --test
